#!/bin/bash

lastmod="$(stat -c %Y "$0")"
while true; do

status=""
if [ -f /tmp/i3 ]; then
	if [ -x /tmp/i3 ]; then
		status="[$(/tmp/i3 | head -n 1)]"
	else
		status="[$(head -n 1 /tmp/i3)]"
	fi
fi

b="$(acpi -b)"
if [ -n "$b" ]; then
	p="${b%%%*}"
	p="${p##* }"
	t="${b% *}"
	if [[ "$b" =~ "Discharging" ]]; then
		t="${t##* }"
		status="$status[$t $p%]"
	elif [[ "$b" =~ "Charging" ]]; then
		t="${t% *}"
		t="${t##* }"
		status="$status[$t⚡$p%]"
	else
		status="$status[$p%]"
	fi
fi

printf "%s\n" "$status[$(date +"%a %b %d ($(date -u +%H))%T")]"
sleep 1

# Check if we've changed, then reload automatically
if [ "$lastmod" -lt "$(stat -c %Y "$0")" ]; then
	exec "$0"
fi

done
