#!/bin/bash
set -euo pipefail

help(){
	echo "Usage: $0 [-l|-m memory <-n name> cmd...|-m memory -u name]"
	echo "-l List cgroup usage by name (-n)"
	echo "-m Memory limit as integer in megabytes"
	echo "-n Name of cgroup"
	echo "-u Update memory limit of cgroup"
}

op="run"
memory=""
while getopts ":m:u:n:lh" opt; do
	case "$opt" in
		m)
			memory="$OPTARG"
		;;
		n)
			name="$OPTARG"
		;;
		u)
			name="$OPTARG"
			op="update"
		;;
		l)
			op="list"
		;;
		h)
			help
			exit
		;;
		*)
			echo "Unknown option"
			help
			exit 1
		;;
	esac
done


# Handle list request first
if [ "$op" = "list" ]; then
	for n in /sys/fs/cgroup/memory/$USER/*; do
		if [ ! -d "$n" ]; then
			continue
		fi
		n="${n##*/}"
		u="$(< /sys/fs/cgroup/memory/$USER/$n/memory.usage_in_bytes)"
		l="$(< /sys/fs/cgroup/memory/$USER/$n/memory.limit_in_bytes)"
		p="$(echo "scale=2;$u * 100 / $l" | bc -l)"
		echo "$n: $(( $u / 1024 / 1024 ))/$(( $l / 1024 / 1024 )) $p%"
	done
	exit
elif [ "$op" = "update" ]; then
	echo $(( $memory * 1024 * 1024 )) > /sys/fs/cgroup/memory/$USER/"$name"/memory.limit_in_bytes
	exit
elif [ "$op" = "run" ]; then
	shift $(( OPTIND - 1 ))
	if [ "$#" = "0" ]; then
		echo "Missing command"
		help
		exit 1
	fi
	if [ -z "$memory" ]; then
		echo "Missing memory"
		help
		exit 1
	fi
	if [[ -z "${name:-}" ]]; then
		name="$1"
	fi

	if [ ! -d /sys/fs/cgroup/memory/$USER ]; then
		echo "Setting up user cgroup with sudo"
		sudo cgcreate -a $USER -t $USER -g memory:"$USER"
	fi
	echo "Setting up cgroup"
	cgcreate -a $USER -t $USER -g memory:"$USER/$name"
	echo $(( $memory * 1024 * 1024 )) > /sys/fs/cgroup/memory/$USER/"$name"/memory.limit_in_bytes
	trap "echo Removing cgroup; cgdelete -g memory:\"$USER/$name\"" EXIT
	cgexec -g memory:"$USER/$name" "$@"
fi
