#!/bin/bash

keypress() {
	echo "Pressing $1"
	curl -m 2 -d '' ${ROKU}keypress/"$1" || echo "Error sending request to ${ROKU}"
}


ROKU="${ROKU:-$((printf "M-SEARCH * HTTP/1.1\nHost: 239.255.255.250:1900\nMan: \"ssdp:discover\"\nST: roku:ecp\n"; sleep 5) | socat -T1 - UDP4-DATAGRAM:239.255.255.250:1900 | awk '/LOCATION/ {gsub("\r", "", $2); print $2}')}"

if [ -z "$ROKU" ]; then
	echo "Didn't find a roku on the network"
	echo "Try setting ROKU to something like \"http://192.168.1.134:8060/\""
	exit 1
else
	echo "Roku found at $ROKU"
fi

key="${1:-}"

if [ -n "$key" ]; then
	keypress "$key"
	exit
fi

while :; do
	read -sn 1 key
	case "$key" in
		w)
			keypress "Home"
		;;
		g)
			keypress "InstantReplay"
		;;
		h)
			keypress "left"
		;;
		j)
			keypress "down"
		;;
		k)
			keypress "up"
		;;
		l)
			keypress "right"
		;;
		i)
			keypress "Info"
		;;
		"")
			keypress "select"
		;;
		\x1b)
			keypress "back"
		;;
		q)
			keypress "back"
		;;
		p)
			keypress "play"
		;;
		"0")
			keypress "VolumeUp"
		;;
		"9")
			keypress "VolumeDown"
		;;
		t)
			keypress Rev
		;;
		y)
			keypress Fwd
		;;
		v)
			echo "free text input mode"
			while read -sn 1 button; do
				case "$button" in 
					"")
						break
					;;
					$'\x1b')
						echo "escape"
						break
					;;
					$'\x7f')
						keypress "Backspace"
					;;
					*)
						keypress "Lit_$button"
					;;
				esac
			done
		;;
		*)
			printf "$key" | hexdump -C
			echo "I don't know how to handle \"$key\""
		;;
	esac
done
